# -*- coding: utf-8 -*-
"""Make_apk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2FWolVoGGVwyk8GsmWWbkalxa7kWyM2

1. Установка пакетов
"""

!pip install buildozer
!sudo apt-get update
!sudo apt-get install -y git unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake

"""2. Загрузка файлов *.py

3. Создание файла buildozer.spec
"""

!buildozer init

"""4. Создание APK"""

!buildozer android release
# !buildozer -v android debug